### ISSUE TITLE
Замечания по CMyList

### ISSUE THREAD

**Issue by oMystique** [oMystique/OOP#15]
1. В методе CMyList<ValueType> & CMyList<ValueType>::operator=(const CMyList & other) нарушается идиома RAII

**Comment by oMystique** [comment]
Учесть исключения при создании объекта типа ValueType

**Comment by oMystique** [comment]
- Перемещающий оператор присваивания
- Конструктор копирования

**Comment by oMystique** [comment]
гарантировать отсутствие исключений при создании пустого списка

**Comment by oMystique** [comment]
Вынести в отдельный метод
if (IsEmpty())
{
    throw runtime_error("List is empty.");
}

**Comment by oMystique** [comment]
Реализовать реверсиный итератор (возможно, через указание итератору способа инкремента в виде lambda-функции)

**Comment by oMystique** [comment]
Для константных (r)begin и (r)end использовать префикс "c"

**Comment by oMystique** [comment]
Реализовать оператор operator!= через operator==

**Comment by oMystique** [comment]
0.5

**Comment by alexey-malov** [comment]
Ознакомьтесь с реверсированным итератором. Возможно, вашу версию реверсивного итератора получится реализовать с его помощью более лаконично
http://www.cplusplus.com/reference/iterator/reverse_iterator/

**Comment by alexey-malov** [comment]
в шаблонной версии избавиться от фиктивной ноды, т.к. она требует наличия конструктора по умолчанию.

**Comment by alexey-malov** [comment]
Из AddToFront перехват исключения убрать, т.к. обработчик ничего не делает

**Comment by alexey-malov** [comment]
устранить пересоздание фиктивных нод, если они уже были созданы

**Comment by alexey-malov** [comment]
AddToFront отрефакторить

**Comment by alexey-malov** [comment]
Append отрефакторить

**Comment by alexey-malov** [comment]
Шаблонный класс проверить на списках элементов, позволяющих моделировать выбрасывание исключений при копировании и присваивании

**Comment by alexey-malov** [comment]
---

**Comment by alexey-malov** [comment]
Для моделирования выбрасывания исключений лучше сделать в mock-классе флаг (throwOnCopy)

**Comment by alexey-malov** [comment]
У итеатора реализовать оператор `->`

**Comment by alexey-malov** [comment]
добавить или найти тест, проверяющий, что begin и end возвращают одинаковые итераторы у пустого списка. Поведение итератора begin сделать идентичным одноименному итератору стандартного списка. поведение тоже желательно проверить
