### ISSUE TITLE
Замечания по MVC-приложению

### ISSUE THREAD

**Issue by alexey-malov** [oMystique/OOP#3]
``` c++
Observable::Observable(CModel *model) :notify(true) {
};
```

для чего передается модель в конструктор?

**Comment by alexey-malov** [comment]
``` c++
void Observable::RemoveObservers() {
    vector<Observer*>::iterator it;
    for (it = observers.begin(); it != observers.end();) {
        Observer *b = *it;
        it = observers.erase(it);
        delete b;
    }
}
```

Обычно ссылки на Observer-ов идут невладеющие, поэтому удалять их здесь неправильно
Можно воспользоваться auto для объявления итератора
Можно использовать range-based for:
for (auto observer: observers)

**Comment by alexey-malov** [comment]
Рекомендую использовать соглашения о стиле кодирования, которые я в группе http://vk.com/oop.blog выложил

**Comment by alexey-malov** [comment]
``` c++
void Observable::NotifyUpdate(String const command) {
    for (auto &observer : observers) {
        observer->Update(this, command);
    }
}
```

Строки, которые вы не меняете, лучше по константной ссылке принимать.
Хранение контекста изменений в строке затрудняет извлечение их оттуда наблюдателем и является источником ошибок

**Comment by alexey-malov** [comment]
``` c++
Observable::~Observable() {
    observers.clear();
}
```

деструктор вектора сам очистит массив наблюдателей

**Comment by alexey-malov** [comment]
``` c++
public:
    CFiguresGraphic();
public:
    virtual void Draw(RenderWindow &window) = 0;
    virtual void ResetFigure(Vector2f const size, Vector2f const pos) = 0;
    virtual FloatRect GetRect() = 0;
public:
    bool isDeleted;
private:
    virtual void SetFigurePosition(Vector2f const pos) = 0;
};
```

В базовом классе следует объявлять деструктор виртуальным
http://stackoverflow.com/questions/461203/when-to-use-virtual-destructors
Методы, не изменяющие состояние объекта. следует объявить константными

**Comment by alexey-malov** [comment]
``` c++
class CModel : public Observer, Observable {
private:
    CView *m_view = nullptr;
...
```

В модели не должно быть ссылок на view

**Comment by alexey-malov** [comment]
``` c++
class CApplicationButton : public CApplicationForm {
```

странно, что кнопка унаследована от формы, которая, в свою очередь, от элементов интерфейса (во множественном числе)

**Comment by alexey-malov** [comment]
``` c++
class CInterfaceElements {
public:
    CInterfaceElements(Vector2f const size, Vector2f const pos, String const name);
    virtual void Draw(RenderWindow &window) const = 0;
    virtual void ProcessEvent(Vector2f const mousePos) = 0;
    virtual FloatRect GetRect() = 0;
    String GetName();
protected:
    Vector2f m_size;
    Vector2f m_pos;
    String m_name;
};
```

зачем нужно "Имя"?

**Comment by alexey-malov** [comment]
пока все плохо

**Comment by sergey-shambir** [comment]
- В файле resources не надо использовать using namespace, глобальный using namespace может вызвать большие проблемы при подключении новых библиотек и долговременной поддержке проекта, это крайне дурной тон. Все using можно писать только в cpp-файле, или внутри другого пространства имён. Проблемный код:

``` cpp
using namespace std;
using namespace sf;
```

Допустимый using в заголовочном файле:

``` cpp
namespace signals
{
    using boost::signals2::Connection;
}
```
- следует создать stdafx.h/stdafx.cpp и настроить предкомпиляцию в секции настроек проекта "C++" -> "Precompiled Headers". У файла stdafx.cpp надо открыть аналогичные настройки и настроить Precompiled Headers на "Create" вместо общепроектного "Use".
- думаю, по несколько раз писать `public: A public: B` не надо, в секциях с одинаковой видимостью повторяться незачем. Проявляется, например, в CApplicationButton.
- класс CShapeGraphic наверное лучше сделать интерфейсом IShapeGraphic, убрав у него всю конкретику (типа поля isDeleted). Надо добавить виртуальный деструктор. Свободные функции GetIntersects и FigureEvent наверное лучше занести в какой-то класс хотя бы в виде статических методов
- реализацию метода CDomainModel::DeleteFigure можно упростить (кстати, сам метод можно переименовать на RemoveInvalidShapes). См. [пример с remove_if](https://github.com/PS-Group/ips-wiki/blob/master/prog_theory/common-issues/vector-for-loop.md)
